### ISSUE TITLE
Help, Please...

### ISSUE THREAD

**Issue by l3m4r94** [ewwink/MD5-Hash-Changer#1]
Hi, it is possible to insert a personal MD5 hash to the file?

**Comment by ewwink** [comment]
it posible but 

> this would take universe scale time
> https://security.stackexchange.com/questions/116095/is-possible-to-force-a-file-to-generate-an-

**Comment by l3m4r94** [comment]
Thanks for the andare, can you update the exe with option to insert personal md5?

**Comment by l3m4r94** [comment]
*answer
