### ISSUE TITLE
[REQUEST]Automatically select all files in a directory, change their MD5 hash and exit the md5 changer

### ISSUE THREAD

**Issue by Markhor123** [ewwink/MD5-Hash-Changer#3]
Is this possible? this will really help me to automate my setup

**Comment by zerodayz1** [comment]
Definitely this, I really would like to be able to select a folder and have it recurse through all files and folders within that. 
Having a cli version of this tool would really help workflow too!
Great work btw! This is a great tool.

**Comment by ewwink** [comment]
added in V1.2.

Thanks
