### ISSUE TITLE
4 bytes added for each hash change when only one is necessary

### ISSUE THREAD

**Issue by Lister0fSmeg** [ewwink/MD5-Hash-Changer#4]
I have noticed that this program adds 4 bytes every time a hash change is done. This is unnecessary because only 1 byte needs to be added to change the file hash.

Having an option for the byte 0 to 255 number to add would be helpful in cases where someone else might of created an identical file. If everyone uses the same numbers then it very easily make the file hash the same. A semi random number might be best.

An even  better idea would be to use a counter and increment the counter for each hash change. That would only need 2 bytes for 65536 hash changes or 4 bytes for over 4 billion hash changes.

**Comment by ewwink** [comment]
its random 2-7 bytes, and thanks for your suggestion.
